USE [BDQualityv]
GO

/****** Object:  UserDefinedFunction [dbo].[FUN_PUNTO]    Script Date: 06/01/2018 22:33:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






/* SQLINES EVALUATION VERSION TRUNCATES VARIABLE NAMES AND COMMENTS. */
/* OBTAIN A LICENSE AT WWW.SQLINES.COM FOR FULL CONVERSION. THANK YOU. */


CREATE FUNCTION [dbo].[FUN_PUNTO](
    @P_PUNTO_VENTA VARCHAR(50) )
  RETURNS VARCHAR(4)
AS
BEGIN
  DECLARE @V_PUNTO              VARCHAR(4);

  IF @P_PUNTO_VENTA   ='FAC PTO VTA 1'
    SET @V_PUNTO   ='F001';
  ELSE IF @P_PUNTO_VENTA='FAC PTO VTA 2' 
    SET @V_PUNTO   ='F002';
  ELSE IF @P_PUNTO_VENTA='FAC PTO VTA 3' 
    SET @V_PUNTO   ='F003';
  ELSE IF @P_PUNTO_VENTA='FAC PTO VTA 4' 
    SET @V_PUNTO   ='F004';
  ELSE IF @P_PUNTO_VENTA='FAC PTO VTA 5' 
    SET @V_PUNTO   ='F005';
  ELSE IF @P_PUNTO_VENTA='FAC PTO CAFET' 
    SET @V_PUNTO   ='F006';
  ELSE IF @P_PUNTO_VENTA='FAC PTO CAFET 2' 
    SET @V_PUNTO   ='F007';
  ELSE IF @P_PUNTO_VENTA='FAC PTO SHOP' 
    SET @V_PUNTO   ='F008';
  ELSE IF @P_PUNTO_VENTA='FAC CUMPLEAÑOS' 
    SET @V_PUNTO   ='F009';
  ELSE IF @P_PUNTO_VENTA='FAC VTA SALIDA' 
    SET @V_PUNTO   ='B001';
  ELSE IF @P_PUNTO_VENTA='FACTURA EXPORTACION'
    SET @V_PUNTO   ='B002';

   
RETURN @V_PUNTO;

END;







GO


